### ISSUE TITLE
Unsafe use of eval

### ISSUE THREAD

**Issue by cristianstaicu** [milojs/proto#1]
In lib/proto_function.js (as compiled in the published npm module), the following use of eval is dangerous:

``` js
function makeFunction(arg1, arg2, funcBody) {
    var name = this, count = arguments.length - 1, funcBody = arguments[count], func, code = '';
    for (var i = 0; i < count; i++)
        code += ', ' + arguments[i];
    code = [
        'func = function ',
        name,
        '(',
        code.slice(2),
        ') {\n',
        funcBody,
        '\n}'
    ].join('');
    eval(code);
    return func;
}
```

As opposed to new Function(), your code do not validate the arguments. Please validate the argument names and the function name by using some regular expression or some more heavy-weighted sanitization like: 
https://www.npmjs.com/package/eval-sanitizer

A similar case is createSubclass method in lib/proto_prototype.js.

**Comment by epoberezkin** [comment]
#2 resolves it
